version: "3.9"
services:
  app:
    build: .
    container_name: app
    env_file:
      - ./.env
    # environment:
    #   NODE_ENV: development
    #   API_PORT: 8000
    #   MONGO_URL: mongodb://mongo:27017
    #   REDIS_URL: redis://redis:6379
    #   RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - mongodb
      - rabbitmq
    ports:
      - 8000:8000
  postgres:
    image: postgres:latest
    container_name: postgres-app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    # Expose port 5432 to the host for DataGrip app use
      - 5432:5432
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis-app
  mongodb:
    image: mongo:latest
    container_name: mongo-app
    ports:
    # Expose port 27017 to the host for DataGrip app use
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password